import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('Seeding database with dental supplies...')

  const supplies = [
    {
      code: 'SUP-001',
      name: 'Nitrile Gloves - Small',
      description: 'Powder-free nitrile examination gloves, size small, box of 100',
      quantity: 250,
      unit: 'box',
      unitPrice: 12.99,
      supplier: 'DentalSupplyCo',
      category: 'consumables',
    },
    {
      code: 'SUP-002',
      name: 'Nitrile Gloves - Medium',
      description: 'Powder-free nitrile examination gloves, size medium, box of 100',
      quantity: 500,
      unit: 'box',
      unitPrice: 12.99,
      supplier: 'DentalSupplyCo',
      category: 'consumables',
    },
    {
      code: 'SUP-003',
      name: 'Nitrile Gloves - Large',
      description: 'Powder-free nitrile examination gloves, size large, box of 100',
      quantity: 300,
      unit: 'box',
      unitPrice: 12.99,
      supplier: 'DentalSupplyCo',
      category: 'consumables',
    },
    {
      code: 'SUP-004',
      name: 'Latex Gloves - Medium',
      description: 'Powdered latex examination gloves, size medium, box of 100',
      quantity: 150,
      unit: 'box',
      unitPrice: 9.99,
      supplier: 'MedicalGear Inc',
      category: 'consumables',
    },
    {
      code: 'SUP-005',
      name: 'Disposable 3-Way Syringe Tips',
      description: 'Sterile disposable syringe tips, pack of 100',
      quantity: 800,
      unit: 'pack',
      unitPrice: 15.50,
      supplier: 'DentalSupplyCo',
      category: 'consumables',
    },
    {
      code: 'SUP-006',
      name: 'Dental Needles 27G',
      description: '27-gauge dental anesthetic needles, box of 100',
      quantity: 400,
      unit: 'box',
      unitPrice: 22.00,
      supplier: 'PrecisionDental',
      category: 'consumables',
    },
    {
      code: 'SUP-007',
      name: 'Dental Needles 30G',
      description: '30-gauge dental anesthetic needles, box of 100',
      quantity: 350,
      unit: 'box',
      unitPrice: 24.00,
      supplier: 'PrecisionDental',
      category: 'consumables',
    },
    {
      code: 'SUP-008',
      name: 'Composite Resin A2',
      description: 'Light-cure composite resin, shade A2, 4g syringe',
      quantity: 75,
      unit: 'syringe',
      unitPrice: 45.00,
      supplier: 'RestoMaterials',
      category: 'materials',
    },
    {
      code: 'SUP-009',
      name: 'Composite Resin A3',
      description: 'Light-cure composite resin, shade A3, 4g syringe',
      quantity: 60,
      unit: 'syringe',
      unitPrice: 45.00,
      supplier: 'RestoMaterials',
      category: 'materials',
    },
    {
      code: 'SUP-010',
      name: 'Dental Amalgam',
      description: 'High-copper dental amalgam capsules, box of 50',
      quantity: 120,
      unit: 'box',
      unitPrice: 85.00,
      supplier: 'AmalgamPlus',
      category: 'materials',
    },
    {
      code: 'SUP-011',
      name: 'Glass Ionomer Cement',
      description: 'Self-cure glass ionomer restorative cement',
      quantity: 45,
      unit: 'unit',
      unitPrice: 38.50,
      supplier: 'RestoMaterials',
      category: 'materials',
    },
    {
      code: 'SUP-012',
      name: 'Dental Bibs - Blue',
      description: 'Disposable patient bibs, blue, pack of 500',
      quantity: 1000,
      unit: 'pack',
      unitPrice: 18.00,
      supplier: 'CleanClinic',
      category: 'consumables',
    },
    {
      code: 'SUP-013',
      name: 'Cotton Rolls - Medium',
      description: 'Sterile cotton rolls, medium size, bag of 2000',
      quantity: 600,
      unit: 'bag',
      unitPrice: 12.00,
      supplier: 'DentalSupplyCo',
      category: 'consumables',
    },
    {
      code: 'SUP-014',
      name: 'Articulating Paper - Blue',
      description: 'Double-sided articulating paper, blue, box of 300 sheets',
      quantity: 200,
      unit: 'box',
      unitPrice: 25.00,
      supplier: 'PrecisionDental',
      category: 'consumables',
    },
    {
      code: 'SUP-015',
      name: 'Dental Floss Threaders',
      description: 'Disposable floss threaders for bridges and braces, pack of 50',
      quantity: 180,
      unit: 'pack',
      unitPrice: 8.50,
      supplier: 'OralCare Plus',
      category: 'consumables',
    },
    {
      code: 'SUP-016',
      name: 'Carbide Burs - FG 330',
      description: 'Friction grip carbide bur #330, pack of 10',
      quantity: 90,
      unit: 'pack',
      unitPrice: 32.00,
      supplier: 'BurMasters',
      category: 'instruments',
    },
    {
      code: 'SUP-017',
      name: 'Diamond Burs - FG 856',
      description: 'Friction grip diamond bur #856, pack of 5',
      quantity: 70,
      unit: 'pack',
      unitPrice: 28.00,
      supplier: 'BurMasters',
      category: 'instruments',
    },
    {
      code: 'SUP-018',
      name: 'Suture - 3-0 Silk',
      description: 'Non-absorbable silk suture, 3-0 with needle, box of 12',
      quantity: 55,
      unit: 'box',
      unitPrice: 42.00,
      supplier: 'SurgicalSupply',
      category: 'consumables',
    },
    {
      code: 'SUP-019',
      name: 'Suture - 4-0 Vicryl',
      description: 'Absorbable polyglactin suture, 4-0 with needle, box of 12',
      quantity: 48,
      unit: 'box',
      unitPrice: 65.00,
      supplier: 'SurgicalSupply',
      category: 'consumables',
    },
    {
      code: 'SUP-020',
      name: 'Prophy Paste - Medium Grit',
      description: 'Fluoride prophy paste, medium grit, mint flavor, jar',
      quantity: 110,
      unit: 'jar',
      unitPrice: 16.50,
      supplier: 'ProhygieneMax',
      category: 'materials',
    },
    {
      code: 'SUP-021',
      name: 'Prophy Cups - Latex Free',
      description: 'Disposable prophy cups, latex-free, bag of 144',
      quantity: 280,
      unit: 'bag',
      unitPrice: 14.00,
      supplier: 'ProhygieneMax',
      category: 'consumables',
    },
    {
      code: 'SUP-022',
      name: 'Scaler Tips - Universal',
      description: 'Universal ultrasonic scaler tips, pack of 3',
      quantity: 65,
      unit: 'pack',
      unitPrice: 55.00,
      supplier: 'UltrasonicDental',
      category: 'instruments',
    },
    {
      code: 'SUP-023',
      name: 'Impression Material - Light Body',
      description: 'Polyvinyl siloxane impression material, light body, cartridge',
      quantity: 95,
      unit: 'cartridge',
      unitPrice: 48.00,
      supplier: 'ImpressionTech',
      category: 'materials',
    },
    {
      code: 'SUP-024',
      name: 'Impression Material - Putty',
      description: 'Polyvinyl siloxane impression material, putty, jar set',
      quantity: 72,
      unit: 'set',
      unitPrice: 68.00,
      supplier: 'ImpressionTech',
      category: 'materials',
    },
    {
      code: 'SUP-025',
      name: 'Gauze Pads 2x2',
      description: 'Sterile gauze pads, 2x2 inches, box of 200',
      quantity: 450,
      unit: 'box',
      unitPrice: 11.00,
      supplier: 'MedicalGear Inc',
      category: 'consumables',
    },
  ]

  for (const supply of supplies) {
    await prisma.supply.upsert({
      where: { code: supply.code },
      update: supply,
      create: supply,
    })
  }

  console.log(`✓ Seeded ${supplies.length} dental supplies`)
}

main()
  .catch((e) => {
    console.error('Error seeding database:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
